accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('resend-verification-email/', views.resend_verification_email, name='resend_verification_email'),
    path('dashbord/', views.dashbord, name='dashbord'),
    path('', views.dashbord, name='dashbord'),
    path('activate/<str:uidb64>/<str:token>/', views.activate, name='activate'),
    path('forgotPassword/', views.forgotPassword, name='forgotPassword'),
    path('password_reset_confirm/<str:uidb64>/<str:token>/', views.password_reset_confirm, name='password_reset_confirm'),
    path('resetpassword/', views.resetpassword, name='resetpassword'),
    #path('my_orders/', views.my_orders, name='my_orders'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('changePassword/', views.changePassword, name='changePassword'),
    #path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),
]

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('', include('settings.urls')),
    path('accounts/', include('accounts.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.utils import timezone
from django.db import models

class MyAccountManager(BaseUserManager):
    
    def create_user(self, email, username, first_name, last_name, phone_number, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        
        email = self.normalize_email(email)
        user = self.model(
            email=email,
            username=username,
            first_name=first_name,
            last_name=last_name,
            phone_number=phone_number,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, first_name, last_name, phone_number, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, username, first_name, last_name, phone_number, password, **extra_fields)


class Account(AbstractBaseUser, PermissionsMixin):

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=254, unique=True)
    phone_number = models.CharField(max_length=50)
    date_joined = models.DateTimeField(default=timezone.now)
    last_login = models.DateTimeField(default=timezone.now)

    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name', 'phone_number']
    
    
    objects = MyAccountManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_superuser

    def has_module_perms(self, app_label):
        return self.is_superuser

    def full_name(self):
        return f'{self.first_name} {self.last_name}'
    
class UserProfile(models.Model):
    user = models.OneToOneField(Account,on_delete=models.CASCADE)
    address_line_1 = models.CharField(blank=True,max_length=100)
    address_line_2 = models.CharField(blank=True,max_length=100)
    profile_picture = models.ImageField(blank=True , upload_to='userprofile/')
    city = models.CharField(blank=True,max_length=30)
    state = models.CharField(blank=True,max_length=30)
    country = models.CharField(blank=True,max_length=30)

    def __str__(self):
        return self.user.first_name

    def full_address(self):
        return f'{self.address_line_1} {self.address_line_2}'
    

accounts/forms.py
from django import forms
from django.forms import ModelForm
from .models import Account,UserProfile

class RegistrationForm(ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter Password',
        'class': 'form-control',
    }))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat Password',
        'class': 'form-control',
    }))

    class Meta:
        model = Account
        fields = ["first_name", "last_name", "phone_number", "email", "password"]

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields["first_name"].widget.attrs['placeholder'] = 'Enter your first name'
        self.fields["last_name"].widget.attrs['placeholder'] = 'Enter your last name'
        self.fields["phone_number"].widget.attrs['placeholder'] = 'Enter your phone number'
        self.fields["email"].widget.attrs['placeholder'] = 'Enter your email'
        self.fields["password"].widget.attrs['placeholder'] = 'Enter your password'
        self.fields["confirm_password"].widget.attrs['placeholder'] = 'Enter your confirm password'

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError("Passwords do not match!")

        return cleaned_data

class UserForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('first_name', 'last_name', 'phone_number')

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)


        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

class UserProfileForm(forms.ModelForm):
    profile_picture = forms.ImageField(required=False, error_messages={'invalid':{'image file only'}},widget=forms.FileInput) # clear path
    class Meta:
        model = UserProfile
        fields = ('address_line_1', 'address_line_2', 'state', 'country', 'city', 'profile_picture')
        
    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)


        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

accounts/views.py
from django.shortcuts import render, redirect ,get_object_or_404 
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout 
from django.contrib.auth.decorators import login_required
from .forms import RegistrationForm ,UserProfileForm ,UserForm
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.utils.encoding import force_bytes, force_str  
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage
from django.contrib.auth import get_user_model
from .models import Account ,UserProfile
from django.http import HttpResponse



User = get_user_model()

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.email.split('@')[0]  # Set username based on email
            user.is_active = False  # Initially set user as inactive until email is verified
            password = form.cleaned_data.get('password')  # Assuming your form has a 'password' field
            user.set_password(password)
            user.save()

            # Send activation email (uncomment and modify as needed)
            current_site = get_current_site(request)
            mail_subject = 'Activate your account.'
            message = render_to_string('accounts/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()

            messages.success(request, 'Please confirm your email address to complete the registration')
            return redirect('login')
    else:
        form = RegistrationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/register.html', context)


def user_login(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)
            messages.success(request, 'Login successful')
            return redirect('home')  # Redirect to home page after successful login
        else:
            messages.error(request, 'Invalid login credentials')
            return redirect('login')  # Redirect back to login page with error message

    return render(request, 'accounts/login.html')



@login_required(login_url='login')
def user_logout(request):
    logout(request)
    messages.success(request, 'You have been logged out.')
    return redirect('home')  

def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Your account has been activated successfully.')
        return redirect('login')
    else:
        messages.error(request, 'Invalid activation link.')
        return redirect('login')



def resend_verification_email(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            user = get_object_or_404(User, email=email)

            if user.is_active:
                messages.info(request, 'Your account is already active.')
            else:
                current_site = get_current_site(request)
                mail_subject = 'Activate your account.'
                message = render_to_string('accounts/acc_active_email.html', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': default_token_generator.make_token(user),
                })
                to_email = form.cleaned_data.get('email')
                email = EmailMessage(mail_subject, message, to=[to_email])
                email.send()

                messages.success(request, 'A new activation link has been sent to your email.')
            return redirect('login')  
    else:
        form = RegistrationForm()
    
    return render(request, 'accounts/resend_verification_email.html', {'form': form})

@login_required(login_url='login')
def dashbord(request):
    # order = Order.objects.order_by('-created_at').filter(user_id=request.user.id,is_ordered=True)
    # order_count = order.count()

    userprofile = UserProfile.objects.get(user_id=request.user.id)
    context = {
        # 'order_count': order_count,
        'userprofile':userprofile,
    }

    return render (request,'accounts/dashbord.html',context)

# @login_required(login_url='login')
# def my_orders(request):
#     order = Order.objects.filter(user=request.user,is_ordered=True).order_by('-created_at')
#     context = {
#         'orders': order,
#         }
#     return render(request,'accounts/my_orders.html',context)


@login_required(login_url='login')
def edit_profile(request):
    userprofile = get_object_or_404(UserProfile,user=request.user)
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = UserProfileForm(request.POST, request.FILES, instance=request.user.userprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile has been updated.')
            return redirect('edit_profile')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = UserProfileForm(instance=request.user.userprofile)
        context = {
            'user_form': user_form,
            'profile_form': profile_form,
            'userprofile':userprofile,
            }
    return render(request,'accounts/edit_profile.html',context)



def forgotPassword(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        if Account.objects.filter(email=email).exists():
            user = Account.objects.get(email=email)

            # Generate and send password reset email
            current_site = get_current_site(request)
            mail_subject = 'Reset your password'
            message = render_to_string('accounts/reset_password_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            to_email = email
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()
            
            messages.success(request, 'Password reset link sent to your email address.')
            return redirect('login')  # Redirect to login page after sending email
        else:
            messages.error(request, 'This email does not exist.')
            return redirect('forgotpassword')  # Redirect back to forgot password form
        
    return render(request, 'accounts/forgotpassword.html')


def password_reset_confirm(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        request.session['uid'] = uid
        messages.success(request,'please reset your password')
        return redirect('resetpassword')
    else:
        messages.error(request, 'Invalid token or link has expired')
        return redirect('login')
    
def resetpassword(request):
    if request.method == 'POST':
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        if password == confirm_password :
            uid = request.session.get('uid')
            user = Account.objects.get(pk=uid)
            user.set_password(password)
            user.save()
            messages.success(request,' we are done successe')
            return redirect('login')
        else:
            messages.error(request,'password dont match ')
            return redirect('resetpassword')
    else:     
        return render (request,'accounts/resetpassword.html')
    
@login_required(login_url='login')
def changePassword(request):
    if request.method == 'POST':
        current_password = request.POST['current_password'] # name = HTML 
        new_password = request.POST['new_password'] # name = HTML 
        confirm_password = request.POST['confirm_password'] # name = HTML 

        user = Account.objects.get(username__exact=request.user.username)

        if new_password == confirm_password:
            success = user.check_password(current_password)
            if success:
                user.set_password(new_password)
                user.save()
                messages.success(request,'Password changed successfully')
                return redirect('changePassword')
            else:
                messages.error(request,'Current password is incorrect')
                return redirect('changePassword')
        else:
            messages.error(request,'New password and confirm password does not match')

accounts/templates/accounts/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:
http://{{ domain }}{% url 'activate' uidb64=uid token=token %}

Thanks for joining us!
The MySite team
{% endautoescape %}

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y bg">
    <div class="container">
        <div class="row">
            <aside class="col-md-3">
                <!-- SIDEBAR -->
                <ul class="list-group">
                    <a class="list-group-item {% if '/dashbord/' in request.path %}active{% endif %}" href="{% url 'dashbord' %}">Dashboard</a>
                    <a class="list-group-item {% if '/edit_profile/' in request.path %}active{% endif %}" href="{% url 'edit_profile' %}">Edit Profile</a>
                    <a class="list-group-item {% if '/changePassword/' in request.path %}active{% endif %}" href="{% url 'changePassword' %}">Change Password</a>
                </ul>
                <br>
                <a class="btn btn-light btn-block" href="{% url 'logout' %}"><i class="fa fa-power-off"></i> <span class="text">Log out</span></a>
                <!-- SIDEBAR END -->
            </aside>
            <main class="col-md-9">
                <article class="card">
                    <header class="card-header">
                        <strong class="d-inline-block mr-3">change your password :</strong>
                    </header>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <form action="{%url 'changePassword' %}" method="post">
                                    {% csrf_token %}

                                    <div class="form-row">
                                        <div class="form-group col-md-12">
                                            <label >current password </label>
                                            <input type="password" name ='current_password' placeholder="Current Password" class='form-control' required>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="form-group col-md-12">
                                            <label>create new  password </label>
                                            <input type="password" name ='new_password' placeholder="create new Password" class='form-control' required>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="form-group col-md-12">
                                            <label>confirm new  password </label>
                                            <input type="password" name ='confirm_password' placeholder="confirm new Password" class='form-control' required>
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-primary">Save changes</button>
                                </form>
                                
                            </div>
                        </div> <!-- row.// -->
                    </div> <!-- card-body .// -->
                </article> <!-- order-group.// -->
            </main>
        </div> <!-- row.// -->
    </div>
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

accounts/templates/accounts/dashbord.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">
    <div class="container">
        <div class="row">
            <aside class="col-md-3">
                <!-- SIDEBAR -->
                <ul class="list-group">
                    <a class="list-group-item {% if '/dashbord/' in request.path %}active{% endif %}" href="{% url 'dashbord' %}">Dashboard</a>
                    <a class="list-group-item {% if '/edit_profile/' in request.path %}active{% endif %}" href="{% url 'edit_profile' %}">Edit Profile</a>
                    <a class="list-group-item {% if '/changePassword/' in request.path %}active{% endif %}" href="{% url 'changePassword' %}">Change Password</a>
                </ul>
                <br>
                <a class="btn btn-light btn-block" href="{% url 'logout' %}"><i class="fa fa-power-off"></i> <span class="text">Log out</span></a>
                <!-- SIDEBAR END -->
            </aside>
                    <main class="col-md-9">
            <article class="card">
            <header class="card-header">
                <strong class="d-inline-block mr-3">logged in as :  </strong>
                <span>{{user.full_name}}</span>
            </header>
            <div class="card-body">
                <div class="row"> 
                    <div class="col-md-6">
                        <div class="card" style="text-align: center;">
                        </div>

                    </div> <!-- row.// -->
                            <div class="col-md-6">
                                <div class="card" style="text-align: center;"> 
                                    <div class="card-body">
                                        <img src="{{userprofile.profile_picture.url}}" alt="user profile pic" width='50' height="50" style='border-radius:50%'>
                                        <p class='mb-0'>{{user.email}}</p>
                                        <p>{{user.phone_number}}</p>

                                    </div>
                                </div>
                            </div>
        
                        </div> <!-- row.// -->
                    </div>

    
            </div> <!-- card-body .// -->
            </article> <!-- order-group.// --> 
        </main>
    </div> <!-- row.// -->
    </div>
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    
    

{% endblock %}

accounts/templates/accounts/dashbord_sidebar.html
<aside class="col-md-3">
    <!-- SIDEBAR -->
    <ul class="list-group">
        <a class="list-group-item {% if '/dashbord/' in request.path %}active{% endif %}" href="{% url 'dashbord' %}">Dashboard</a>
        <a class="list-group-item {% if '/edit_profile/' in request.path %}active{% endif %}" href="{% url 'edit_profile' %}">Edit Profile</a>
        <a class="list-group-item {% if '/changePassword/' in request.path %}active{% endif %}" href="{% url 'changePassword' %}">Change Password</a>
    </ul>
    <br>
    <a class="btn btn-light btn-block" href="{% url 'logout' %}"><i class="fa fa-power-off"></i> <span class="text">Log out</span></a>
    <!-- SIDEBAR END -->
</aside>

accounts/templates/accounts/forgotPassword.html
<!-- forgotpassword.html -->
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <h2>Forgot Password</h2>
    <form method="POST" action="{% url 'forgotPassword' %}">
        {% csrf_token %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        <div class="form-group">
            <label for="id_email">Email address</label>
            <input type="email" class="form-control" id="id_email" name="email" required>
        </div>
        <button type="submit" class="btn btn-primary">Reset Password</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<section class="section-conten padding-y" style="min-height: 84vh">

        <div class="card mx-auto" style="max-width: 380px; margin-top: 20px;">
            <div class="card-body">
                <h4 class="card-title mb-4">Sign in</h4>
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}

                <form action="{% url 'login' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="email" class="form-control" placeholder="Email Address" name="email" required>
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control" placeholder="Password" name="password" required>
                    </div>
                    <div class="form-group">
                        <a href="{% url 'forgotPassword' %}" class="float-right">Forgot password?</a>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block">Login</button>
                    </div>
                </form>
            </div> <!-- card-body -->
        </div> <!-- card -->
        
        <p class="text-center mt-4">Don't have an account? <a href="{% url 'register' %}">Sign up</a></p>
</section>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}

{% block body %}




<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">

<!-- ============================ COMPONENT REGISTER   ================================= -->
<div class="card mx-auto" style="max-width: 520px; margin-top: 40px;">
    <article class="card-body">
        <header class="mb-4">
            <h4 class="card-title">Sign up</h4>
        </header>
        <form action="{% url 'register' %}" method="POST">
            {% csrf_token %}

            <div class="form-row">
                <div class="col-md-6 form-group">
                    <label for="id_first_name">First name</label>
                    {{ form.first_name }}
                    <!-- Use |add_class:"form-control" to add Bootstrap form-control class -->
                </div>
                <div class="col-md-6 form-group">
                    <label for="id_last_name">Last name</label>
                    {{ form.last_name }}
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="id_email">Email address</label>
                    {{ form.email }}
                </div>
                <div class="form-group col-md-6">
                    <label for="id_phone_number">Phone</label>
                    {{ form.phone_number }}
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="id_password">Create password</label>
                    {{ form.password }}
                </div>
                <div class="form-group col-md-6">
                    <label for="id_conform_password">Repeat password</label>
                    {{ form.confirm_password }}
                </div>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block">Register</button>
            </div>

            <!-- Display form errors if any -->
            {% if form.errors %}
            <div class="alert alert-danger">
                <ul>
                    {% for field, errors in form.errors.items %}
                        {% for error in errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                </ul>
            </div>
            {% endif %}
        
        </form>
    </article><!-- card-body end -->
</div><!-- card end -->

<p class="text-center mt-4">Have an account? <a href="{% url 'login' %}">Log In</a></p>

<!-- ============================ COMPONENT REGISTER  END.// ================================= -->


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->




</body>
</html>

{% endblock %}

accounts/templates/accounts/resend_verification_email.html
<!-- resend_verification_email.html -->
{% extends 'base.html' %}
{% block body %}
<h2>Resend Verification Email</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Resend Email</button>
</form>
{% endblock %}

accounts/templates/accounts/reset_password_email.html
<h2>Password Reset</h2>
<p>Hello {{ user.username }},</p>
<p>We received a request to reset your password for our site. Please click the link below to reset your password:</p>
<p><a href="{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}" class="btn">Reset Password</a></p>
<p>If you didn't request this, you can safely ignore this email.</p>
<p>Thanks,<br> The Team</p>

accounts/templates/accounts/resetpassword.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<section class="section-conten padding-y" style="min-height: 84vh">

        <div class="card mx-auto" style="max-width: 380px; margin-top: 20px;">
            <div class="card-body">
                <h4 class="card-title mb-4">reset password</h4>
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}

                <form action="{% url 'resetpassword' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="password" class="form-control" placeholder="create Password" name="password" required>
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control" placeholder="confirm Password" name="confirm_password" required>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block"> reset </button>
                    </div>
                </form>
            </div> <!-- card-body -->
        </div> <!-- card -->
        
        <p class="text-center mt-4">Don't have an account? <a href="{% url 'register' %}">Sign up</a></p>
</section>
{% endblock %}